### ISSUE TITLE
Гайда нет

### ISSUE THREAD

**Issue by Dott-rus** [thecreeez/MGBridge#2]
Добавьте гайд по развёртыванию моста, ну или просто команды для этого

**Comment by thecreeez** [comment]
Установка тривиальная для node-приложений. Просто введи npm install (В теории он должен сам поставиться с нодой, если нет - https://www.npmjs.com/). Потом для запуска введи node index.js в контексте папки (или создай .bat файл в папке с мостом в котором будет node index.js)
